site_name: Apuntes de Redes Locales &copy;Antonio Díaz Santamaría
site_author: Antonio Díaz Santamaría
theme:
  name: 'material'
  palette:
    primary: 'indigo'  # Color primario
    accent: 'red'      # Color de acento
  features:
    - navigation.sections  # Expansión y colapso de las secciones
    - navigation.instant   # Desplazamiento rápido
extra_css:
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear
  - 'assets/css/stylesheets.css'
nav:
  - Índice: 'index.md'
  - Unidad 1: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 2: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 3: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 4: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 5:
      - 5.1. Introducción: 'u05/05-01.md'
      - 5.2. Direccionamiento IPv4:
          - 5.2.1 Estructura de una dir. IP: 'u05/05-02-01.md'
          - 5.2.2 Clases de redes: 'u05/05-02-02.md'
          - 5.2.3 IP privada y pública: 'u05/05-02-03.md'
          - 5.2.4 Máscara de red: 'u05/05-02-04.md'
          - 5.2.5 Configuración en Windows: 'u05/05-02-05.md'
          - 5.2.6 Direccionamiento IPv6:
              - 5.2.6.1 Introducción: 'u05/05-02-06-01.md'
              - 5.2.6.2 Dirección IPv6: 'u05/05-02-06-02.md'
      - 5.3. Segmentación de una red:
          - 5.3.1 Ventajas de la segmentación: 'u05/05-03-01.md'
          - 5.3.2 Subneteo: 'u05/05-03-02.md'
          - 5.3.3 VLSM: 'u05/05-03-03.md'
      - 5.4. Funcionamiento de los Switches:
          - 5.4.1 Definición y funcionamiento: 'u05/05-04-01.md'
          - 5.4.2 Tabla CAM: 'u05/05-04-02.md'
          - 5.4.3 Aprendizaje de las direcciones MAC: 'u05/05-04-03.md'
          - 5.4.4 Mantenimiento de la Tabla CAM: 'u05/05-04-04.md'
          - 5.4.5 Diferencia entre switches capa 2 y capa 3: 'u05/05-04-05.md'
      - 5.5. Enrutamiento:
          - 5.5.1 Introducción al Enrutamiento: 'u05/05-05-01.md'
          - 5.5.2 Tablas de enrutamiento: 
              - 5.5.2.1 Introducción a las tablas de enrutamiento: 'u05/05-05-02-01.md'
              - 5.5.2.2 Tabla de enrutamiento de un Host: 'u05/05-05-02-02.md'
              - 5.5.2.3 Tabla de enrutamiento de un Router: 'u05/05-05-02-03.md'
          - 5.5.3 Tipos de enrutamiento: 'u05/05-05-03.md'
      - 5.6 Herramientas para comprobar la conectividad:
          - 5.6.1 Herramientas disponibles: 'u05/05-06-01.md'
          - 5.6.2 Comando Ping: 'u05/05-06-02.md'
          - 5.6.3 Comando tracert / traceroute: 'u05/05-06-03.md'
          - 5.6.4 Comando arp: 'u05/05-06-04.md'
          - 5.6.5 Comando ipconfig / ifconfig: 'u05/05-06-05.md'
      - 5.7. VLANS:
          - 5.7.1 ¿Que son?: 'u05/05-07-01.md'
          - 5.7.2 Tipos: 'u05/05-07-02.md'
          - 5.7.3 Configuración Básica: 'u05/05-07-03.md'
          - 5.7.4 Medidas de seguridad: 'u05/05-07-04.md'
      - 5.8. Redes Inalámbricas:
          - 5.8.1 Características: 'u05/05-08-01.md'
          - 5.8.2 Componentes de una WLAN: 'u05/05-08-02.md'
          - 5.8.3 Topología de las WLAN: 'u05/05-08-03.md'
          - 5.8.4 Protocolos y Estándares comunes: 'u05/05-08-04.md'
          - 5.8.5 Asociación y Autenticación en WLAN: 'u05/05-08-05.md'
          - 5.8.6 Seguridad: 'u05/05-08-06.md'
      - 5.9. La Seguridad en las redes: 'u05/05-09.md'
      - 5.10. Protocolos:
          - 5.10.1 Protocolo DHCP: 'u05/05-10-01.md'
          - 5.10.2 Protocolo DNS: 'u05/05-10-02.md'
          - 5.10.3 Protocolo ARP: 'u05/05-10-03.md'
          - 5.10.4 Protocolo BOOTP: 'u05/05-10-04.md'
          - 5.10.5 Protocolo ICMP: 'u05/05-10-05.md'
  - Unidad 6:
      - 6.1. Introducción: 'u06/06-01.md'
      - 6.2. Instalación y primeros pasos: 'u06/06-02.md'
      - 6.3. Interfaz y Herramientas: 'u06/06-03.md'
      - 6.4. Primera red: 'u06/06-04.md'
      - 6.5. Configuración de Switchs y Routers:
          - 6.5.1 Introducción: 'u06/06-05-01.md'
          - 6.5.2 Configuración de Switchs: 'u06/06-05-02.md'
          - 6.5.3 Modos de Operación: 'u06/06-05-03.md'
          - 6.5.4 Cisco IOS: 'u06/06-05-04.md'
          - 6.5.5 Configuración de los Switchs: 'u06/06-05-05.md'
          - 6.5.6 VLANs: 'u06/06-05-06.md'
          - 6.5.7 Conexión Switch-Patch Panel: 'u06/06-05-07.md'
          - 6.5.8 Routers: 'u06/06-05-08.md'
          - 6.5.9 Enlace Serial: 'u06/06-05-09.md'
      - 6.6. Diagnóstico: 'u06/06-06.md'
      - 6.7. Calidad en Instalaciones: 'u06/06-07.md'
      - 6.8. Buenas Prácticas: 'u06/06-08.md'

