site_name: Apuntes de Redes Locales &copy;Antonio Díaz Santamaría
site_author: Antonio Díaz Santamaría
theme:
  name: 'material'
  palette:
    primary: 'indigo'  # Color primario
    accent: 'red'      # Color de acento
  features:
    - navigation.sections  # Expansión y colapso de las secciones
    - navigation.instant   # Desplazamiento rápido
extra_css:
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear
nav:
  - Índice: 'index.md'
  - Unidad 1: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 2: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 3: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 4: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 5:
      - 5.1. Introducción: 'u05/u05_01.md'
      - 5.2. Estructura de una dir. IP: 'u05/u05_02.md'
      - 5.3. Clases de redes: 'u05/u05_03.md'
      - 5.4. IP privada y pública: 'u05/u05_04.md'
      - 5.5. Máscara de red: 'u05/u05_05.md'
      - 5.6. Subneteo: 'u05/u05_06.md'
      - 5.7. VLSM: 'u05/u05_07.md'
      - 5.8. Tablas de enrutamiento: 'u05/u05_08.md'
      - 5.9. Protocolo DHCP: 'u05/u05_Prot01.md'
      - 5.10. Protocolo DNS: 'u05/u05_Prot02.md'

