site_name: Apuntes de Redes Locales &copy;Antonio Díaz Santamaría
site_author: Antonio Díaz Santamaría
theme:
  name: 'material'
  palette:
    primary: 'indigo'  # Color primario
    accent: 'red'      # Color de acento
  features:
    - navigation.sections  # Expansión y colapso de las secciones
    - navigation.instant   # Desplazamiento rápido
extra_css:
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear
  - 'assets/css/stylesheets.css'
nav:
  - Índice: 'index.md'
  - Unidad 1: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 2: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 3: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 4: []  # Si no tienes contenido, puedes dejarlo vacío de esta forma, o eliminar la entrada.
  - Unidad 5:
      - 5.1. Introducción: 'u05/05-01.md'
      - 5.2. Direccionamiento IPv4:
          - 5.2.1 Estructura de una dir. IP: 'u05/05-02-01.md'
          - 5.2.2 Clases de redes: 'u05/05-02-02.md'
          - 5.2.3 IP privada y pública: 'u05/05-02-03.md'
          - 5.2.4 Máscara de red: 'u05/05-02-04.md'
      - 5.3. Segmentación de una red:
          - 5.3.1 Subneteo: 'u05/05-03-01.md'
          - 5.3.2 VLSM: 'u05/05-03-02.md'
      - 5.4. Enrutamiento:
          - 5.4.1 Tablas de enrutamiento: 'u05/05-04-01.md'
          - 5.4.2 Tipos de enrutamiento: 'u05/05-04-02.md'
          - 5.4.3 Herramientas para comprobar la conectividad: 'u05/05-04-03.md'
      - 5.5. Protocolos:
          - 5.5.1 Protocolo DHCP: 'u05/05-05-01.md'
          - 5.5.2 Protocolo DNS: 'u05/05-05-02.md'
          - 5.5.3 Protocolo ARP: 'u05/05-05-03.md'
          - 5.5.4 Protocolo BOOTP: 'u05/05-05-04.md'
          - 5.5.5 Protocolo ICMP: 'u05/05-05-05.md'

